version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: messaging-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: messaging_app
    volumes:
      - mongodb_data:/data/db
    networks:
      - messaging-network

  redis:
    image: redis:7-alpine
    container_name: messaging-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - messaging-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: messaging-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/messaging_app?authSource=admin
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - messaging-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - messaging-network

volumes:
  mongodb_data:
  redis_data:

networks:
  messaging-network:
    driver: bridge
